### ISSUE TITLE
Do Go Proverbs next?

### ISSUE THREAD

**Issue by coolaj86** [ewjoachim/zen-of-python#3]
"Go Proverbs" is the Spiritual Successor to Zen of Python.

https://go-proverbs.github.io/

```txt
Go Proverbs
Simple, Poetic, Pithy

Don't communicate by sharing memory, share memory by communicating.
Concurrency is not parallelism.
Channels orchestrate; mutexes serialize.
The bigger the interface, the weaker the abstraction.
Make the zero value useful.
interface{} says nothing.
Gofmt's style is no one's favorite, yet gofmt is everyone's favorite.
A little copying is better than a little dependency.
Syscall must always be guarded with build tags.
Cgo must always be guarded with build tags.
Cgo is not Go.
With the unsafe package there are no guarantees.
Clear is better than clever.
Reflection is never clear.
Errors are values.
Don't just check errors, handle them gracefully.
Design the architecture, name the components, document the details.
Documentation is for users.

Don't panic.
```

**Comment by ewjoachim** [comment]
This seems lovely. I don't have plans for a next one yet, but you're welcome to copy the style and make it your own :)

> A little copying is better than a little dependency.

:stuck_out_tongue:  :heart:

**Comment by coolaj86** [comment]
I did not copy the style per se, but I did make a printable version:
https://github.com/BeyondCodeBootcamp/go-proverbs/

I really do like the line numbers.

I'm creating a Code Style guide that references these rules as in the form of "P13" and "G8" as justification for the Code Style rule. I'll post that here as well if I get it to the point that it's ready to share.

**Comment by ewjoachim** [comment]
Lovely!

Thank you :)
